# Generated by Django 4.0 on 2021-12-23 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('valid_syntax', models.BooleanField()),
                ('disposable', models.BooleanField()),
                ('webmail', models.BooleanField()),
                ('deliverable', models.BooleanField()),
                ('gibberish', models.BooleanField()),
                ('spam', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='phone_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('phone_valid', models.BooleanField(default=False)),
                ('phone_type', models.CharField(max_length=15, null=True)),
                ('phone_region', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('country_code', models.CharField(max_length=6, null=True)),
                ('country_prefix', models.CharField(max_length=6, null=True)),
                ('international_number', models.CharField(max_length=20, null=True)),
                ('local_number', models.CharField(max_length=20, null=True)),
                ('e164', models.CharField(max_length=20, null=True)),
                ('carrier', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('number', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('email_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validetorapp.email_details')),
                ('phone_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validetorapp.phone_details')),
            ],
        ),
    ]
